### ISSUE TITLE
TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by Arcyvilk** [kometh0616/crown-bot#6]
I'm using the newest version of the bot.

```
 TypeError: Cannot read property 'id' of undefined
data:    index.js:1095 -     at CrownsCommand.run (/home/arcyvilk/crown-bot/src/commands/crowns.js:43:30)
data:    index.js:1095 -     at CrownsCommand.execute (/home/arcyvilk/crown-bot/src/handler/Command.js:14:24)
data:    index.js:1095 -     at module.exports (/home/arcyvilk/crown-bot/src/events/message.js:11:19)
data:    index.js:1095 -     at CrownBot.emit (events.js:160:13)
data:    index.js:1095 -     at MessageCreateHandler.handle (/home/arcyvilk/crown-bot/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
data:    index.js:1095 -     at WebSocketPacketManager.handle (/home/arcyvilk/crown-bot/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:105:65)
data:    index.js:1095 -     at WebSocketConnection.onPacket (/home/arcyvilk/crown-bot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:333:35)
data:    index.js:1095 -     at WebSocketConnection.onMessage (/home/arcyvilk/crown-bot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:296:17)
data:    index.js:1095 -     at WebSocket.onMessage (/home/arcyvilk/crown-bot/node_modules/ws/lib/event-target.js:120:16)
data:    index.js:1095 -     at WebSocket.emit (events.js:160:13)
data:    index.js:1095 -     at Receiver.receiverOnMessage (/home/arcyvilk/crown-bot/node_modules/ws/lib/websocket.js:789:20)
data:    index.js:1095 -     at Receiver.emit (events.js:160:13)
data:    index.js:1095 -     at Receiver.dataMessage (/home/arcyvilk/crown-bot/node_modules/ws/lib/receiver.js:422:14)
data:    index.js:1095 -     at Receiver.getData (/home/arcyvilk/crown-bot/node_modules/ws/lib/receiver.js:352:17)
data:    index.js:1095 -     at Receiver.startLoop (/home/arcyvilk/crown-bot/node_modules/ws/lib/receiver.js:138:22)
data:    index.js:1095 -     at Receiver._write (/home/arcyvilk/crown-bot/node_modules/ws/lib/receiver.js:74:10)
data:    index.js:1095 -     at doWrite (_stream_writable.js:407:12)
data:    index.js:1095 -     at writeOrBuffer (_stream_writable.js:393:5)
data:    index.js:1095 -     at Receiver.Writable.write (_stream_writable.js:290:11)
data:    index.js:1095 -     at TLSSocket.socketOnData (/home/arcyvilk/crown-bot/node_modules/ws/lib/websocket.js:864:35)
data:    index.js:1095 -     at TLSSocket.emit (events.js:160:13)
data:    index.js:1095 -     at addChunk (_stream_readable.js:269:12)
```

The related code:

```
let user
        if (args.length > 0) {
            if (cmds.includes(args[0])) {
                const command = require(`./crowns/${args[0]}`)
                await command.run(client, message, args.slice(1))
                return
            } else {
                user = message.mentions.members.first()
            }
        } else {
            user = message.member
        }
        const crowns = await client.models.crowns.findAll({
            where: {
                guildID: message.guild.id,
                userID: user.id // <= here the bug triggers
            }
        })
```

**Comment by kometh0616** [comment]
Did you try to use crowns command with usernames and/or tags? Because it only works with mentions.
